# link: https://leetcode.com/problems/find-the-difference/
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        """
        Find the added letter in the shuffled string.
        Given two strings 's' and 't', where 't' is generated by shuffling 's' and adding one
        more letter at a random position, this function returns the letter that was added.

        Args:
        - s (str): The original string.
        - t (str): The shuffled string with an added letter.

        Returns:
        - str: The added letter in the shuffled string.
        """
        result = 0
        for char in s:
            result ^= ord(char)
        for char in t:
            result ^= ord(char)

        return chr(result)


# Time complexity: O(n)
# Space complexity: O(1)
